SHELL = /bin/sh
INSTALL = install -c
MKDIR = install -d 

destdir = ../bin/

srcdir = .

SRC =  	APFControl.py Heimdallr.py UCSCScheduler_V2.py x_gaussslit.py apflog.py Visible.py ExposureCalculations.py



install:
	$(MKDIR) $(destdir)
	$(INSTALL) $(SRC) $(destdir)
